"""
tests/test_ingestion.py
-----------------------
Pytest tests for the Veriscribe Phase-1 ingestion pipeline.

Tests run against two synthetic PDFs generated by conftest.py:
  - pdf_a: single-column, text-only, 3 pages.
  - pdf_b: table on page 1, embedded image on page 2.

Assertions
~~~~~~~~~~
1. All returned chunks have valid normalised bboxes (all values in [0, 1]).
2. reading_order_index is strictly monotonically increasing per page.
3. No chunk_type="text" chunk substantially overlaps a chunk_type="table"
   chunk's bbox on the same page (dedup check).
4. At least one chunk is returned per PDF.
5. Only valid chunk_type literals are used.
6. Table chunks on pdf_b page 1 carry non-empty table_data.
"""

from __future__ import annotations

import pathlib
from collections import defaultdict
from typing import List

import pytest

from ingestion.models import Chunk
from ingestion.pipeline import parse_document


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _bbox_overlap(
    a: tuple[float, float, float, float],
    b: tuple[float, float, float, float],
) -> float:
    """Return the intersection / min-area ratio for two normalised bboxes."""
    ix0 = max(a[0], b[0])
    iy0 = max(a[1], b[1])
    ix1 = min(a[2], b[2])
    iy1 = min(a[3], b[3])
    if ix1 <= ix0 or iy1 <= iy0:
        return 0.0
    inter = (ix1 - ix0) * (iy1 - iy0)
    area_a = (a[2] - a[0]) * (a[3] - a[1])
    area_b = (b[2] - b[0]) * (b[3] - b[1])
    min_area = min(area_a, area_b)
    return inter / min_area if min_area > 0 else 0.0


# ---------------------------------------------------------------------------
# Common assertions, usable for both PDFs
# ---------------------------------------------------------------------------

def assert_valid_chunks(chunks: List[Chunk]) -> None:
    """Apply assertions that must hold for any well-formed parse result."""
    assert len(chunks) > 0, "parse_document must return at least one chunk"

    # Group by page
    by_page: dict[int, List[Chunk]] = defaultdict(list)
    for c in chunks:
        by_page[c.page_number].append(c)

    for page_num, page_chunks in by_page.items():
        # Sort by reading_order_index for ordered checks
        ordered = sorted(page_chunks, key=lambda c: c.reading_order_index)

        # --- 1. Valid normalised bboxes ------------------------------------
        for c in ordered:
            x0, y0, x1, y1 = c.bbox
            assert 0.0 <= x0 <= 1.0, f"page {page_num}: x0={x0} out of [0,1]"
            assert 0.0 <= y0 <= 1.0, f"page {page_num}: y0={y0} out of [0,1]"
            assert 0.0 <= x1 <= 1.0, f"page {page_num}: x1={x1} out of [0,1]"
            assert 0.0 <= y1 <= 1.0, f"page {page_num}: y1={y1} out of [0,1]"
            assert x1 > x0, f"page {page_num}: bbox has x1 <= x0"
            assert y1 > y0, f"page {page_num}: bbox has y1 <= y0"

        # --- 2. reading_order_index is monotonically increasing ------------
        indices = [c.reading_order_index for c in ordered]
        for i in range(len(indices) - 1):
            assert indices[i] < indices[i + 1], (
                f"page {page_num}: reading_order_index not strictly increasing "
                f"at positions {i} ({indices[i]}) and {i+1} ({indices[i+1]})"
            )

        # --- 3. No text chunk substantially overlaps a table chunk ---------
        text_chunks = [c for c in ordered if c.chunk_type == "text"]
        table_chunks = [c for c in ordered if c.chunk_type == "table"]
        for tc in text_chunks:
            for tbl in table_chunks:
                overlap = _bbox_overlap(tc.bbox, tbl.bbox)
                assert overlap < 0.3, (
                    f"page {page_num}: text chunk {tc.chunk_id} overlaps "
                    f"table chunk {tbl.chunk_id} by {overlap:.1%}"
                )

        # --- 4. Only valid chunk_type literals ----------------------------
        valid_types = {"text", "table", "chart_candidate"}
        for c in ordered:
            assert c.chunk_type in valid_types, (
                f"Invalid chunk_type '{c.chunk_type}' on page {page_num}"
            )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

class TestPdfA:
    """Tests for the single-column, text-only PDF."""

    def test_returns_chunks(self, pdf_a: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_a), document_id="doc_a")
        assert len(chunks) > 0

    def test_valid_chunks(self, pdf_a: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_a), document_id="doc_a")
        assert_valid_chunks(chunks)

    def test_covers_all_pages(self, pdf_a: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_a), document_id="doc_a")
        pages_seen = {c.page_number for c in chunks}
        # pdf_a has 3 pages; all should have at least one chunk
        assert len(pages_seen) == 3, f"Expected 3 pages, got {pages_seen}"

    def test_no_table_chunks(self, pdf_a: pathlib.Path) -> None:
        """Text-only PDF should produce no table chunks."""
        chunks = parse_document(str(pdf_a), document_id="doc_a")
        assert not any(c.chunk_type == "table" for c in chunks)

    def test_document_id_propagated(self, pdf_a: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_a), document_id="doc_a")
        assert all(c.document_id == "doc_a" for c in chunks)

    def test_chunk_ids_unique(self, pdf_a: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_a), document_id="doc_a")
        ids = [c.chunk_id for c in chunks]
        assert len(ids) == len(set(ids)), "Duplicate chunk_ids detected"


class TestPdfB:
    """Tests for the multi-element PDF (table + image)."""

    def test_returns_chunks(self, pdf_b: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_b), document_id="doc_b")
        assert len(chunks) > 0

    def test_valid_chunks(self, pdf_b: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_b), document_id="doc_b")
        assert_valid_chunks(chunks)

    def test_table_detected(self, pdf_b: pathlib.Path) -> None:
        """pdf_b page 1 has a ruled table — at least one table chunk expected."""
        chunks = parse_document(str(pdf_b), document_id="doc_b")
        table_chunks = [c for c in chunks if c.chunk_type == "table"]
        assert len(table_chunks) >= 1, "No table chunk detected in pdf_b"

    def test_table_data_non_empty(self, pdf_b: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_b), document_id="doc_b")
        for c in chunks:
            if c.chunk_type == "table":
                assert c.table_data is not None
                assert len(c.table_data) > 0
                assert any(
                    any(cell.strip() for cell in row)
                    for row in c.table_data
                ), "table_data contains only empty cells"

    def test_covers_multiple_pages(self, pdf_b: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_b), document_id="doc_b")
        pages_seen = {c.page_number for c in chunks}
        assert len(pages_seen) >= 2, f"Expected chunks on ≥2 pages, got {pages_seen}"

    def test_no_text_table_overlap(self, pdf_b: pathlib.Path) -> None:
        """Explicit overlap test for dedup correctness."""
        chunks = parse_document(str(pdf_b), document_id="doc_b")
        by_page: dict[int, List[Chunk]] = defaultdict(list)
        for c in chunks:
            by_page[c.page_number].append(c)

        for page_num, page_chunks in by_page.items():
            text_chunks = [c for c in page_chunks if c.chunk_type == "text"]
            table_chunks = [c for c in page_chunks if c.chunk_type == "table"]
            for tc in text_chunks:
                for tbl in table_chunks:
                    overlap = _bbox_overlap(tc.bbox, tbl.bbox)
                    assert overlap < 0.3, (
                        f"page {page_num}: text/table overlap={overlap:.1%}"
                    )

    def test_chunk_ids_unique(self, pdf_b: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_b), document_id="doc_b")
        ids = [c.chunk_id for c in chunks]
        assert len(ids) == len(set(ids)), "Duplicate chunk_ids detected"


class TestPdfC:
    """Regression tests for full-width spanning-block bbox preservation.

    pdf_c has:
      - One full-width heading that physically spans ~87% of page width.
      - Two genuine side-by-side text columns below the heading.

    These tests lock in the fix that prevents full-width blocks from being
    incorrectly clamped to a single narrow column band.
    """

    def test_returns_chunks(self, pdf_c: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_c), document_id="doc_c")
        assert len(chunks) > 0

    def test_valid_chunks(self, pdf_c: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_c), document_id="doc_c")
        assert_valid_chunks(chunks)

    def test_chunk_ids_unique(self, pdf_c: pathlib.Path) -> None:
        chunks = parse_document(str(pdf_c), document_id="doc_c")
        ids = [c.chunk_id for c in chunks]
        assert len(ids) == len(set(ids)), "Duplicate chunk_ids detected"

    def test_full_width_heading_bbox_not_clamped(self, pdf_c: pathlib.Path) -> None:
        """Full-width heading must keep >=95% of its natural extracted x-width.

        The heading text 'Full-Width Heading Spanning Both Columns' is drawn
        across the full text area of the page.  The spanning-block classifier
        must NOT clamp this to a single narrow column band.
        """
        import fitz

        # Measure the actual raw bbox from PyMuPDF directly (ground truth)
        doc = fitz.open(str(pdf_c))
        page = doc[0]
        pw = page.rect.width
        raw_blocks = page.get_text("blocks")
        heading_blocks = [
            b for b in raw_blocks
            if b[6] == 0 and "Full-Width Heading" in b[4]
        ]
        doc.close()
        assert heading_blocks, "Heading block not found in pdf_c by PyMuPDF"

        raw_x0 = heading_blocks[0][0] / pw
        raw_x1 = heading_blocks[0][2] / pw
        natural_width = raw_x1 - raw_x0

        # Now check what parse_document returns for that heading
        chunks = parse_document(str(pdf_c), document_id="doc_c")
        heading_chunks = [
            c for c in chunks
            if c.chunk_type == "text" and c.text and "Full-Width Heading" in c.text
        ]
        assert heading_chunks, (
            f"Heading chunk not found in parse_document output. "
            f"All text chunks: {[(c.text[:40] if c.text else None) for c in chunks if c.chunk_type=='text']}"
        )

        chunk_width = heading_chunks[0].bbox[2] - heading_chunks[0].bbox[0]

        # The chunk width must be >=95% of the natural (unclamped) width
        assert chunk_width >= natural_width * 0.95, (
            f"Full-width heading bbox was clamped: "
            f"chunk_width={chunk_width:.4f}, natural_width={natural_width:.4f} "
            f"(ratio={chunk_width/natural_width:.3f} < 0.95). "
            f"This indicates the spanning-block fix regressed."
        )

    def test_two_columns_detected(self, pdf_c: pathlib.Path) -> None:
        """Column detection on pdf_c should produce exactly 2 distinct col_index
        values (0 and 1) among the non-spanning text chunks.

        We verify this via the pipeline output: left-column and right-column
        body lines are narrow (width ~0.16) and should each anchor one column;
        the full-width heading is a spanning block (col_index == -1) and must
        not distort the column count.
        """
        import fitz
        from ingestion.layout import order_blocks, detect_header_footer_zones

        doc = fitz.open(str(pdf_c))
        all_pages = [doc[i] for i in range(len(doc))]
        hbands, fbands = detect_header_footer_zones(all_pages)
        page = doc[0]
        blocks = order_blocks(page, hbands, fbands)
        doc.close()

        # Non-spanning blocks must occupy exactly 2 distinct column indices
        col_indices = {
            b["col_index"] for b in blocks if not b.get("spanning", False)
        }
        assert col_indices == {0, 1}, (
            f"Expected non-spanning blocks to be in columns {{0, 1}}, "
            f"got col_indices={col_indices}. "
            f"Column detection is producing the wrong number of columns for pdf_c."
        )

        # Spanning blocks must all have col_index == -1
        spanning_blocks = [b for b in blocks if b.get("spanning", False)]
        assert spanning_blocks, "Expected at least one spanning block (the heading)"
        assert all(b["col_index"] == -1 for b in spanning_blocks), (
            f"Spanning blocks have wrong col_index: "
            f"{[b['col_index'] for b in spanning_blocks]}"
        )


# ---------------------------------------------------------------------------
# Regression: Table 1 tight-bbox detection on real Mistral 7B PDF (page 2)
# ---------------------------------------------------------------------------

import pathlib as _pathlib

_ARXIV_PDF = _pathlib.Path("output/arxiv_paper.pdf")


@pytest.mark.skipif(
    not _ARXIV_PDF.exists(),
    reason="output/arxiv_paper.pdf not present — skipping live-PDF regression",
)
class TestMistralTable1Regression:
    """Regression tests locking in the tight Table 1 detection introduced
    by the two-stage candidate-region + crop approach in ingestion/tables.py.

    Guards against a previous false-positive where the blunt text-strategy
    fallback matched the entire page body (area ≈ 48.8%) as a single table.
    """

    @pytest.fixture(scope="class")
    def page2_chunks(self):
        chunks = parse_document(str(_ARXIV_PDF), document_id="arxiv_doc")
        return [c for c in chunks if c.page_number == 2]

    def test_table_chunk_exists_on_page2(self, page2_chunks):
        """At least one table chunk must be detected on page 2."""
        table_chunks = [c for c in page2_chunks if c.chunk_type == "table"]
        assert table_chunks, (
            "No table chunk detected on page 2 of arxiv_paper.pdf. "
            "Table 1 (architecture parameters) should be detected."
        )

    def test_table1_bbox_area_under_5pct(self, page2_chunks):
        """The tightest table chunk on page 2 must have normalised bbox area < 5%.

        This locks in the two-stage localisation fix. If this regresses to the
        whole-page false positive the area would be ~48%, failing this assertion.
        """
        table_chunks = [c for c in page2_chunks if c.chunk_type == "table"]
        areas = [
            (c.bbox[2] - c.bbox[0]) * (c.bbox[3] - c.bbox[1])
            for c in table_chunks
        ]
        min_area = min(areas)
        assert min_area < 0.05, (
            f"Smallest table chunk on page 2 has normalised area {min_area:.1%}, "
            f"expected < 5%. This likely means the whole-page false-positive has "
            f"returned. Check ingestion/tables.py candidate localisation logic."
        )

    def test_table1_has_parameter_value_data(self, page2_chunks):
        """The detected table must contain the architecture parameter rows
        (Parameter/Value header, dim, n_layers, etc.) — confirming it is
        genuinely Table 1 and not some other fragment."""
        table_chunks = [c for c in page2_chunks if c.chunk_type == "table"]
        # Find the smallest-area table (Table 1 is compact; footnote region larger)
        table_chunks_sorted = sorted(
            table_chunks,
            key=lambda c: (c.bbox[2] - c.bbox[0]) * (c.bbox[3] - c.bbox[1]),
        )
        tbl = table_chunks_sorted[0]
        assert tbl.table_data, "Table chunk has no table_data"
        flat_text = " ".join(
            cell for row in tbl.table_data for cell in row if cell
        ).lower()
        # Must contain at least some of the known architecture parameter keys
        known_params = {"dim", "n_layers", "head_dim", "n_heads", "vocab_size"}
        found = known_params & set(flat_text.split())
        assert found, (
            f"Table 1 data doesn't contain expected architecture params. "
            f"Flat text: {flat_text[:200]!r}"
        )
